# -*- coding: utf-8 -*-
"""CSE110-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dOtEaa5jk04SwdBDTh5G_GQ9SWQxTSy3
"""

print("Hello World")

str1="Hello "
str2="World"
print(str1 + str2)

str1="Hello"
str2="World"
print(str1 +" "+ str2)

print(2+3)

Season= "Fall"
Year= 2022
print(Season)
print(Year)

Season= "Fall"
Year= "\n2022"
print(Season + Year)

input1= input("What is your name?")
print(input1)

input1= input("What is your name?")
print("Your name is", input1)

input1= input("What is your name?")
print("Your name is" +" "+ input1)

Name= input("Insert your name-")
print(f"Your name is {Name}")

M= int(input("M="))
N= int(input("N="))
print(f"{M}^{N}: {M**N}")

m= int(input())
n= int(input())
s= m**n
print(m, "^", n, ":", s)

x= int(input("Insert weight "))
print( x//4*4 )

x= int(input("Insert weight "))
print( x-x%4 )

A= int(input("A="))
B= int(input("B="))
C= int(input("C="))
D= float(input("D="))
print(int(A**C+B*A-D/3))

A= int(input("The number of chocolates="))
print("Each friend will receive", A//3, "chocolates")
print("The number of remaining chocolates is", A%3)

M= input()
N= input()
print(N + M)

A= input()
print(A[0])

x= int(input())
if(x%2==0):
   print("True")
else:
   print("False")

x= input()
inputs=[ x ]
max= x
min= x
print(x)
total= int(x)
while True:
  x= input()
  if(x =="Done"):
    break
  else:
    if(int(x)%2==0 and int(x)>=0):
        inputs.append(x)
        total+= int(x)
        print(x)
    if(x>max):
        max=x
    if(x<min and int(x)>=0):
        min=x
print("Average", total/len(inputs))
print("Max", max)
print("Min", min)

x=int(input("Enter height="))
for i in range(x, 0, -1):
    for j in range(i):
        print( "*",end='')
    print("")

rows = int(input("Enter number of rows: "))

k = 0

for i in range(1, rows+1):
    for space in range(1, (rows-i)+1):
        print(end="  ")

    while k!=(2*i-1):
        print("* ", end="")
        k += 1

    k = 0
    print()

myList = [10, 20, 30, 40, 50, 40, 30, 20, 10]
p = 5
q = 0
r = 0
while q < 9:
    r = (p + q - r) % 9
    while r < q:
        p = p + r
        myList[q] = myList[q] - myList[r] - int(str(p) + "3")
        r += 1
    print(myList[q])
    p = p - q
    q += 25 % 12
print(len(myList) == q)

print(int(str(-1)+"3"))

myList = [10, 20, 30, 40, 50, 40, 30, 20, 10]
p = 5
q = 0
r = 0
while q < 9:
    r = (p + q - r) % 9
    print("loop r", r)
    while r < q:
        p = p + r
        print("loop p", p)
        myList[q] = myList[q] - myList[r] - int(str(p) + "3")
        print("loop mylist", myList[q])
        r += 1
    print(myList[q])
    p = p - q
    print("loop p", p)
    q += 25 % 12
    print("loop q", q)
print(len(myList) == q)

l1 = [5, 4, 3, 4, 5, 4, 8, 2, 1]
j = 1

while j <= 3:
    for i in range (1,j+1):
        k= int(str(i)+str(j))%9
        l1[j] = l1[j] - l1[k]
        print(l1[i])
    j+=1
    print(l1[j])
print(j%3!=0)

myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
b = myList
while (index1 < 10):
   myList[index1] += myList[index2 % 10] + 5
   print("kmkm", myList[index1])
   index2 = 1
   while (index2 < index1):
       myList[index1] = b[index2 % 5] - index1
       print("kmkm2", myList[index1])
       index2 += 3
   print(myList[index1])
   index1 += 1

myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
b = myList
while (index1 < 10):
   myList[index1] += myList[index2 % 10] + 5
   index2 = 1
   while (index2 < index1):
       myList[index1] = b[index2 % 5] - index1
       index2 += 3
   print(myList[index1])
   index1 += 1

myList1 = [5,6,1,4,6]
var1 = 2
var3 = myList1
while(var1 < 5):
     var2 = 1
     while(var2 <= var1):
         print(myList1[var2])
         var3[var2] = myList1[var2] + var3[var1] - 9
         var2 = var2 + 1
     var1 = var1 + 1
print(len(var3) in myList1)

givenList = [10, 4, 20, 9, 30, 10, 5, 40, 3, 7]
a = 1
b = 5
c = 2
newList = givenList
while(a<10):
  b = (b + a) % 2
  while(b<a):
    givenList[a] = newList[a]- givenList[b]+c
    b = b+1
  print(givenList[a])

  a = a+1
  c += 2
print(10 in givenList)

