# -*- coding: utf-8 -*-
"""CSE110-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zCNCgBRlHfRp82_QZj8o5_aoNZlfw8tj
"""

#task 1
List1= []
for i in range(5):
  input1= int(input())
  List1.append(input1)
  print(f"Numbers in the list: {List1}")

#task 2
input1= input()[1:-1]
list1= input1.split(", ")
for i in range(len(list1)):
  list1[i]= int(list1[i])
if len(list1)>= 4:
  print(list1[2:-2])
else:
  print("Not possible")

#task 3
List1=[]
for i in range(5):
  input1= int(input())
  List1.append(input1)
print(f"Printing values from the list in reverse order:")
for i in List1[::-1]:
  print(i)

#task 4
input1= input()[1:-1]
list1= input1.split(", ")
list2= []
for i in list1:
  list2.append(int(i)**2)
print(list2)

#task 5
List1= ["hey", "there", "", "what's", "", "up", "", "?"]
List2= []
for i in List1:
  if i== "":
    continue
  else:
    List2.append(i)
print("Original List: ", List1)
print("Modified List: ", List2)

#task 6
input1 = input()
list1 = input1.split(",")
max= int(list1[0])
for i in range(len(list1)):
    list1[i]= int(list1[i])
    if(list1[i]>max):
      max= list1[i]
print("My list: ", list1)
print(f"Largest number in the list is {max} which was found at index {list1.index(max)}")

#task 7
List_one= [1, 3, 5, 7, 9, 10]
List_two= [2, 4, 6, 8]
print(List_one[:-1] + List_two)

#task 8
list_one= [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_two= [10, 11, 12, -13, -14, -15, -16]
list_three= []
for i in list_one:
  if i%2==0:
    list_three.append(i)
for i in list_two:
  if i%2==0:
    list_three.append(i)
print(list_three)

#task 9
input1 = input()
list1 = []
list2= []
String1 = ""
for i in range(len(input1)):
    if ord(input1[i]) in range(48,58):
        String1 += input1[i]
    elif input1[i] == " ":
        list1.append(int(String1))
        String1 = ""
    if i+1 == len(input1) and String1!= "":
        list1.append(int(String1))
for i in list1:
    if i%2!=0:
      list2.append(i)
print("List: ", list1, "\nMod list:", list2)

#task 10
input1= input()
List1= input1.split(", ")
List2= []
for i in range(len(List1)):
  List1[i]= int(List1[i])
  if List1[i] not in List2:
    List2.append(List1[i])
print("Input List: ", List1)
print("Modified List: ", List2)

#task 11
List_one= [1, 4, 3, 2, 5]
List_two= [6, 9, 2, 7]
count=0
for i in List_one:
  for j in List_two:
    if i==j:
      count+=1
if count>=1:
  print("True")
else:
  print("False")