# -*- coding: utf-8 -*-
"""CSE110-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bDLFeqaFS1ET6HDugNzP2i2cbqnTm3kM
"""

#task 1 a
counter = 24
while counter>= -6:
  if counter == -6:
    print(counter, end = "")
  else:
    print(counter, end = ", ")
  counter = counter - 6

#task 1 b
counter = -10
while counter<= 20:
  if counter == 20:
    print(counter, end = "")
  else:
    print(counter, end = ", ")
  counter = counter + 5

#task 1 c
counter = 18
while counter<= 63:
  if counter == 63:
    print(counter, end = "")
  else:
    print(counter, end = ", ")
  counter = counter + 9

#task 1 d
for i in range(6):
  if i==5:
    print((18 + 9*(i))*(-1)**i, end = "")
  else:
    print((18 + 9*(i))*(-1)**i, end = ", ")

#task 2 break
x= input("Enter the name of your favourite car: ")
y= int(input("Enter a number: "))
print(f"\n{x}"*y)

#task 2 loop
x= input("Enter the name of your favourite car: ")
y= int(input("Enter a number: "))
for i in range(y):
  print(x)

#task 3
total=0
for i in range(601):
  if(i%7 == 0 and i%9 == 0):
    total+= i
print(total)

#task 4
total=0
for i in range(601):
  if(i%7 == 0 and i%9 == 0):
    pass
  elif(i%7 == 0 or i%9 == 0):
    total+= i
print(total)

#task 5
for i in range(10, 51):
  if(i%2 == 0):
    pass
  else:
    print(i, end = " ")

#task 6
total = 0
n= int(input())
for i in range(1, n+1):
  total += (i**2)*((-1)**(i-1))
print(total)

#task 6 import
import math
i = int(input("Enter range: "))
y = 0
for n in range(1,i+1):
  y += math.pow(n,2)*math.pow(-1,n-1)
print(y)

#task 7
sum = 0
count = 0
for i in range(0, 10):
  x = int(input(""))
  if(x%2 == 0):
    pass
  else:
    sum+= x
    count += 1
avg = sum/count
print( f"The total of the odd numbers is {sum} and their average is {avg}")

#task 8
total = 0
N= int(input("Enter a number: "))
for i in range(1, N+1):
    if(i%7==0):
      total+=i
print(total)

#task 9
total= 0
for i in range(1, 6):
  x= int(input())
  total+=x
  print(total)

#task 10 siam soln
N = int(input())
while N!=0:
  if N//10!=0:
    print(N%10, end=", ")
  elif N//10==0:
    print(N%10)
  N//=10

#task 10 sir soln
n = int(input())
for i in range(len(str(n))):
  if n//10!=0:
    print(n%10, end=", ")
    n= n//10
  else:
    print(n%10)

#task 11
count= 0
N= int(input())
while N!=0:
  if N//10!=0:
    count+=1
  elif N//10==0:
    count+=1
  N//=10
print(count)

#task 12
n = int(input())
for i in range(len(str(n))):
  if ((len(str(n)))>1):
    print(n//(10**((len(str(n)))-1)), end=", ")
  else:
    print(n//(10**((len(str(n)))-1)))
  n= n%(10**((len(str(n)))-1))

#task 13
count = 0
x= int(input())
for i in range(1, x+1):
  if x%i==0:
    count+=1
    print(i)
print(f"Total {count} divisors.")

#task 14
x= int(input())
sum = 0
for i in range(1, x):
  if(x%i==0):
    sum+= i
if(sum==x):
    print(f"{x} is a perfect number")
else:
    print(f"{x} is not a perfect number")

#task 15
x= int(input())
count=0
for i in range(1, x+1):
  if(x%i==0):
    count+=1
if(count==2):
  print(f"{x} is a prime number")
else:
  print(f"{x} is not a prime number")

#task 16
y= int(input("Enter quantity: "))
x= int(input("Enter values: "))
max= x
min= x
total= x
for i in range(1, y):
  x= int(input("Enter value: "))
  total+= x
  if(x>max):
    max=x
  if(x<min):
     min=x
print("Maximum", max)
print("Minimum", min)
print("Average is", total/y)

#task 17
N= int(input("Enter height="))
for i in range(N):
    for j in range(N):
        print("+",end=" ")
    print()

#task 18
M= int(input("Enter height= "))
N= int(input("Enter length= "))
for i in range(M):
    for j in range(1, N+1):
        print(j, end="")
    print()

#task 19
N= int(input("Enter height= "))
for i in range(N):
    for j in range(1, i+2):
        print(j ,end="")
    print()

#task 20 trace check
x = 0
print("x:", x)
p =0
print("p:", p)
sum = 0
print("sum:", sum)
p = 1
print("p:", p)
x = 2
print("x:", x)
q = None
print("q:", q)
sum = 0
print("sum:", sum)
while p < 12:
    q = x + p - (sum + 7 / 3) / 3.0 % 2
    print("q:", q)
    sum = sum + x + int(q)
    print("sum:", sum)
    x += 1
    print("x:", x)
    print(sum)
    if x > 5:
        p += 4 / 2
        print("p:", p)
    else:
        p += (3 % 1)
        print("p:", p)
sum = int(sum + p)
print("sum:", sum)
print(sum)

print(10+11-(108+7/3)/3.0%2)

print(3%1)

#task 21 trace check
x = 0
p = 0
sum = 0
p = 1
x = 2
q = 0.0
sum = 0
while (p < 10) :
  q = x + p - (sum + int(5 / 3)) / 3.0 % 2
  sum = sum + x + int(q)
  x += 1
  print(sum)
  if (x > 5) :
    p += int(4 / 2)
  else :
    p += 3 % 1
sum = sum + p
print(sum)

print(9 + 9 - (78+ int(5 / 3)) / 3.0 % 2)

#task 22 trace check
x = y = 0
sum = 0
while (x < 10):
  y = x - 3
  while (y < 3):
    sum = x - y * 2
    print(sum)
    y = y + 1
  if (x > 7):
    x += 1
  else:
    x += 3
sum = x - y * 2
print(sum)

print(0 - -3 * 2 )

#task 22 trace auto check
x = y = 0
sum = 0
while (x < 10):
  y = x - 3
  print(f"loop y {y}" )
  while (y < 3):
    sum = x - y * 2
    print(f"loop sum {sum}" )
    print(sum)
    y = y + 1
    print(f"loop y {y}" )
  if (x > 7):
    x += 1
    print(f"loop x {x}" )
  else:
    x += 3
    print(f"loop x {x}" )
sum = x - y * 2
print(sum)

#task 23 trace check
x = 0
y = 0
sum = 0
p = 0.0
while (x < 10):
    y = x // 2
    while (y < x):
        p = (x + 10.0) / 2
        sum = (sum % 2) + x - y * 2 + int(p)
        print(sum)
        y = y + 2
    if (x > 5):
        x += 1
    else:
        x += 2

#task 23 trace auto check
x = 0
y = 0
sum = 0
p = 0.0
while (x < 10):
    y = x // 2
    print(f"loop y {y}" )
    while (y < x):
        p = (x + 10.0) / 2
        print(f"loop p {p}" )
        sum = (sum % 2) + x - y * 2 + int(p)
        print(sum)
        y = y + 2
        print(f"loop y {y}" )
    if (x > 5):
        x += 1
        print(f"loop x {x}" )
    else:
        x += 2
        print(f"loop x {x}" )

#task 24 trace check
test = 1
j = 0
k = 100
while (k > 0):
  while ( j < k ):
    test = k + j -21
    print(str(1 + int (test / 2)))
    j += 10
  k -= 10
test = 1
j = 0
k = 100

#task 24 trace auto check
test = 1
j = 0
k = 100
while (k > 0):
  while ( j < k ):
    test = k + j -21
    print(f"loop test {test}" )
    print(str(1 + int (test / 2)))
    j += 10
    print(f"loop j {j}" )
  k -= 10
  print(f"loop k {k}" )
test = 1
j = 0
k = 100