# -*- coding: utf-8 -*-
"""CSE110-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LgMZpb0wtzt7vxN44lECZf589Mf_36DE
"""

a= int(input("Enter first number="))
b= int(input("Enter second number="))
print("Sum=", a+b)
print("Product", a*b)
print("Difference=", a-b)

var_1 = input('Please enter the first number: ')
var_2 = input('Please enter the second number: ')

print(type(var_1))
print(type(var_2))

var_3 = int(var_1)
var_4 = int(var_2)

total = var_3 + var_4
product = var_3 * var_4
difference = var_3 - var_4

print("Sum =", total)
print("Product =", product)
print("Difference =", difference)

import math
a= float(input("Enter the radius r="))
print("Area is=", math.pi*a**2)
print("Circumference is=", 2*math.pi*a)

a= int(input("Enter first number="))
b= int(input("Enter second number="))
if(a>b):
  print("First is greater")
elif(a<b):
  print("Second is greater")
else:
  print("The numbers are equal")

a= int(input("Enter first number="))
b= int(input("Enter second number="))
if(a>b):
  print(a-b)
elif(a<b):
  print(b-a)
else:
  print(0)

x= int(input())
if(x%2==0):
   print("The number is Even")
else:
   print("The number is Odd")

x= int(input())
if(x%2==0 or x%5==0):
   print(x)
else:
   print("Not a multiple of 2 OR 5")

x= int(input())
if(x%2==0 and x%5==0):
  print("Multiple of 2 and 5 both")
elif(x%2==0 or x%5==0):
   print(x)
else:
   print("Not a multiple we want")

x= int(input())
if(x%2==0 and x%5==0):
  print(x)
else:
   print("Not a multiple of 2 AND 5 both")

x= int(input("Enter number of seconds= "))
h= x//3600
m1= x%3600
m2= m1//60
s= m1%60
print("Hours:", h, "Minutes:", m2, "Seconds:", s )

x= int(input("Enter number of seconds= "))
h= x//3600
m= (x%3600)//60
s= (x%3600)%60
print("Hours:", h, "Minutes:", m, "Seconds:", s )

x= int(input())
if(x in range(0,169)):
  if(x<=40):
    print(200*x)
  if(x>40):
    print(8000 + (x-40)*300)
elif(x<0):
  print("Hour cannot be negative")
else:
  print("Impossible to work more than 168 hours weekly")

S= int(input())
if(S<100):
  print(3000-(125*(S**2)))
elif(S>100):
  print(12000/(4+((S**2)/14900)))

x= int(input())
if(x in range(0,24)):
  if(x>=4 and x<=6):
    print("Breakfast")
  elif(x>=12 and x<=13):
    print("Lunch")
  elif(x>=16 and x<=17):
    print("Snacks")
  elif(x>=19 and x<=20):
    print("Dinner")
  else:
    print("Patience is a virtue")
else:
  print("Wrong time")

x= int(input())
if(x in range(0,101)):
  if(x>=90):
    print("A")
  elif(x>=80 and x<=89):
    print("B")
  elif(x>=70 and x<=79):
    print("C")
  elif(x>=60 and x<=69):
    print("D")
  elif(x>=50 and x<=59):
    print("E")
  elif(x<50):
    print("F")
else:
  print("Invalid Marks")

x= int(input("Enter distance:"))
y= int(input("Enter time:"))
z= ((x/1000)/(y/3600))
if(z<60):
  print(z, "km/h \n Too slow. Needs more changes.")
if(z>=60 and z<=90):
  print(z, "km/h \n Velocity is okay. The car is ready!")
if(z>90):
  print(z, "km/h \n Too fast. Only a few changes should suffice.")

x= float(input("Enter CGPA"))
y= int(input("Enter cREDITS"))
if(x>=3.8 and y>=30):
  if(x>= 3.80 and x<=3.89):
    print("The student is eligible for a waiver of 25 percent.")
  if(x>= 3.90 and x<=3.94):
    print("The student is eligible for a waiver of 50 percent.")
  if(x>= 3.95 and x<=3.99):
    print("The student is eligible for a waiver of 75 percent.")
  if(x== 4.00):
    print("The student is eligible for a waiver of 100 percent.")
else:
  print("The student is not eligible for a waiver")

p = 5
q = 6
r = 9
sum = 0
if (p < 12):
    print(r + 2)
else:
    print(r + p)
if (q > 20):
    print(r + 19)
elif (q <= 6):
    print(q + 3)
else:
    print(p + q + r)
if (r > 15):
    print(r)
elif (r == 0):
    print(p + q)
else:
    print(p)
if (sum != 0):
    print(3)
else:
    print(sum + 32)
if (p>0 and r<10):
    print(p+r)
else:
    print(p-r)

var1 = var2 = var3 = var4 = var5 = var6 = False
result1 = False
result2 = False
result3 = False
result4 = False
result5 = False
result6 = False
result7 = False
result8 = False
result9 = False
result10 = False
var1 = 4 > 3 - 1
var2 = var1 and False
var3 = True
var4 = False
var5 = True
var6 = var3 and False
result1 = (var1 or var2) and (8 * 10 > 45)
result2 = (var1 or var2) and (result1 and False)
result3 = (var1 and result1) or result2
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or var2) and not(result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and (var5 or var6)) and True
result9 = ((result2 and var2) or (result7 and var1)) and False
result10 = not(var1 and True)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

x= int(input())
if(x%2!=0 and x%5!=0):
   print(x)
else:
   print("No")

x= int(input())
if(x%2!=0 or x%5!=0):
   print(x)
else:
   print("No")

x= int(input("Enter no. of canvas: "))
y= int(input("Enter no. of paint tubes: "))
z= (x*120)+(y*75)
if(z>=0 and z<=299):
  print("Previous total:", z, "\nNew total after discount:", z)
if(z>=300 and z<=499):
  print("Previous total:", z, "\nNew total after discount", z-10)
if(z>=500 and z<=749):
  print("Previous total:", z, "\nNew total after discount", z-20)
if(z>=750 and z<=999):
  print("Previous total:", z, "\nNew total after discount", z-50)
if(z>=1000):
  print("Previous total:", z, "\nNew total after discount", z-150)

x= input()
#y= x[ : : -1]
pos= x[len(x)-3: :1]
neg= x[-3: : 1]
print(pos[ : : -1], neg[ : : -1])

x= int(input())
y= ((x-32)*.56)
if(y<20):
  print(y, "degrees C \nWinter")
if(y>=20 and y<=25):
  print(y, "degrees C \nAutumn")
if(y>25 and y<30):
  print(y, "degrees C \nSpring")
if(y>=30):
  print(y, "degrees C \nSummer")