# -*- coding: utf-8 -*-
"""CSE110-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRgz3jqi8Xxjs5Qt207nzztq3-8WJqCk
"""

#task 1
x= input()
y= x[ : : -1]
print(y)

#task 2
x= input()
y= int(input())
z= x[y:  : -1]
w= x[y+1: : 1]
print(z+w)

#task 3 siam soln
user_input = input("Enter your string: ")
binary = True
for i in user_input:
  if not(i is "0" or i is "1"):
    binary = False
    break
if binary:
  print("Binary Number")
else:
  print("Not a Binary Number")

#task 4
x= input()
y= len(x)
if(x[-3: :1]=="est"):
  print(x)
elif(x[-2: :1]=="er"):
  print(x[ : y-2 :1]+ "est")
elif(y>3):
  print(x[: :]+ "er")
elif(y<4):
  print(x)

#task 5
x= input()
y= len(x)
for i in range(y):
  print(x[ : i+1: 1])

#task 6 explanation
str1="labclass"
str2="lol"
#ord() #character to ASCII value
#chr() #ASCII value to character
#ord(str1[0])
ord(str1[0])==ord(str2[0])


#mukhostho ASCII range from 48 to 57 digits
#Formula for ease: in ASCII----> upper case + 32= lower case

#task 6
x= input()
y= len(x)
a= 0
for i in range(y):
  print(f"\n{x[a]} : {ord(x[a])}")
  a+=1

#task 7
x= input()
for i in x:
  if i=="z":
    print("a", end="")
  else:
    print(chr(ord(i)+1), end="")

#task 8
x= input()
x1= x[1: :2]
for i in x1:
  print(chr(ord(i)-32), end="")

#task 9
x= input()
y= ""
for i in x:
  if(i==y):
    pass
  else:
    print(i, end="")
    y=i

#task 10
x= input()
y= x.index(", ")
z1= x[ : y :1]
z2= x[y+2: :1]
if len(z2)>=len(z1):
  for i in range(len(z1)):
    print(z1[i]+z2[i], end="")
  if i<= len(z2)-1:
      print(z2[i+1: :1])
else:
  for i in range(len(z2)):
    print(z1[i]+z2[i], end="")
  if i<= len(z1)-1:
      print(z1[i+1: :1])

#task 10 siam
user_input = input("Enter your string: ")
str_sep = user_input.index(", ")
str1 = user_input[:str_sep:1]
str2 = user_input[str_sep+2::1]
if len(str2)>=len(str1):
  for i in range(len(str1)):
    print(str1[i]+str2[i], end="")
  if i <= len(str2)-1:
    print(str2[i+1::1])
else:
  for i in range(len(str2)):
    print(str1[i]+str2[i], end="")
  if i <= len(str1)-1:
    print(str1[i+1::1])

#task 11
i = 10
while(i >= -20):
    if(i < 0):
        test = " != "
        test = str(i//2) + test + str(int(i/2))
    else:
        test = " == "
        test = str(i//2) + test + str(int(i/2))
    print(test)
    i -= 5

#task 12
test = ""
i = 0
j = 0
k = 15
test = "-->"
while i < 5:
    j = k - 1
    k -= 1
    while j > 10:
        test = str(i + j) + "-->" + test
        print(test)
        j -= 1
    i += 1

#task 13
test = ""
i = 5
j = 0
k = 15
while i< 10:
    k-=1
    j = k
    while j > 10:
        if (j % 2) == 0:
            test = "<--"
            test = str(test) + str(i) + str(2) + "-->" + str(int(j / 2))
        else:
            test = "-->"
            test = "-->" + str(int(i / 2)) + str(test) + str(j)
        print(test)
        j = j-1
    i+=1

#task 14
test = ""
i = 5
j = 0
k = 15
while (i< 10):
    k-=1
    j = k
    while (j > 10 ):
        if j % 2 == 0:
            test = "<--"
            test = test + str( i) + '3' + "-->" + str(j // 3)
        else:
            test = "-->"
            test = "-->" + str((i // 3)) + test + str(j)
        print(test)
        j -=1
    i+=1

#task 15
i=0
j=0
k=15
test = '<--cat'
while i < 5:
    k -= 1
    j = k
    while j > 10:
        if j % 2 == 0:
            test += '-->'
            test = test + str(i) + str(j // 2)
        else:
            test += '<--'
            test = test + str(i // 2) + str(j)
        print(test)
        j-=1
    i+=1

#lab mid kothin q
x= input()
y= input()
check= ""
count= 0
for i in x:
  check +=i
  if check not in y:
    break
  count+=1

w1= x[:count]
w2= x[count:]
print("W1: ", w1, "W2: ", w2)

common= ""
for i in range(len(w1)):
  for j in range(i+1, len(w1)):
    if x[i:j] in w2 and len(w1[i:j]) > len(common):
      common= w1[i:j]
    else:
      common= "no common"
print("Common: ", common)

#lab mid 56 q
x= input()
y= ""
count = 0
for i in x:
  if ord(i) in range(97, 122):
    if i=="a":
      y+= "v"
    elif i=="b":
      y+= "w"
    elif i=="c":
      y+= "x"
    elif i=="d":
      y+= "y"
    elif i=="e":
      y+= "z"
    else:
      y+= chr(ord(i)-5)
  if i == "$":
    y+= "!"
  if i == "#":
    y+= " "
  if i == "/":
    y+= ","
  if i == "1":
    y+= "."
for i in y:
  if i =="!":
    break
  else:
    count+=1

print("Message: ", y)
print("Imposter: ", y[ :count])

#mid set A trace
var1 = 0
r = 0
while var1 <= 5:
    var2 = 1
    while var2 <= var1:
        var2 = var2 + 1
        if var2 == 4 or var2 == 5:
            continue
            print(var1 - var2 * 2)
        elif var1 % 4 > 1:
            print(var1 - var2 - (18 // var1))
        else:
            r = var1 * var2 - int(21 / var2)
            print(r)
    var1 = var1 + 1

#mid set B trace
var1 = 0
r = 1
while var1 <= 5:
    var2 = 1
    while var2 <= var1:
        var2 = var2 + 1
        if var2 == 4 or var2 == 5:
            continue
            print(var1 - var2 * 2)
        elif var1 % 3 > 1:
            print(var1 - var2 - (21 // var1))
        else:
            r = var1 * var2 - int(17 / var2)
            print(r)
    var1 = var1 + 1

i = 0
k = 20702291
while i < 10:
  j = 1
  while j <= 2:
    if i < 2:
      print(k % 10)
      k = k // 10
    elif i < 5:
      print(k // 10**(i - 1) % 10)
    elif i == 6:
      print(k // 100000)
    else:
      print(k // 10**(9-i) % 10)
    j += 1
    i += 1
  if i < 6:
    print("-")
    i += 1

i=1
h=1
sum=0
while i<10:
  j=i*15
  while j<=25:
    k= i+j*4**i+h+3%2**h/2+sum
    sum= sum +7
    if j%2==0 or sum%2==0:
      print("k:", int(k))
    else:
      p="-"
      p+= str(j + sum) + "-->" +str(j) + "<--"
      print("p:", p)
    j= j+6*j%2+j%2+1
  print("j:", j)
  i+=j%4+1
print("sum:", sum)

i=1
print("i loop:", i)
h=1
print("h loop:", h)
sum=0
print("sum loop:", sum)
while i<10:
  j=i*15
  print("j loop:", j)
  while j<=25:
    k= i+j*4**i+h+3%2**h/2+sum
    print("k loop:", k)
    sum= sum +7
    print("sum loop:", sum)
    if j%2==0 or sum%2==0:
      print("k:", int(k))
    else:
      p="-"
      p+= str(j + sum) + "-->" +str(j) + "<--"
      print("p:", p)
    j= j+6*j%2+j%2+1
    print("j loop:", j)
  print("j:", j)
  i+=j%4+1
  print("i loop:", i)
print("sum:", sum)

j= int(input())
print(j+6*j%2+ j%2+1)

x= input()
y= int(input())
z=""
for i in x:
  if ord(i) in range(65, 91) or ord(i) in range(97, 122):
    z+= chr(ord(i)-y)
print(z)

x=input()
y=""
for i in x:
    if ord(i) in range(65,71) or ord(i) in range(97,103) or i in "-:":
      y+= i
    else:
      break
if len(y)==17:
  print("Valid")
else:
   print("Invalid")

x= input()
for i not in "aeiou":
  x-=i
  x+=i
print(x)

x= int(input())
y=""
if x==1:
  print("Factorial of 1= 1")
elif x==0:
  print("Factorial of 0= 1")
else:
  if x%2==0:
    for i in range(x):
      y= str(i)
      print(f"{x}*"+{x-int(y)}+"!")