# -*- coding: utf-8 -*-
"""CSE110-8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIbBzI8vrar7l9bNGewvJZWCvW-tfhmf
"""

#task 1
def bubblelist(arr):
  for i in range(0, len(arr), 1):
    for j in range(0, len(arr)-1, 1):
      if(arr[j+1]<arr[j]):
        arr[j+1], arr[j]= arr[j], arr[j+1]
  return arr
my_list = [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
bubblelist(my_list)

#task 2
def selectionasc(arr):
  for i in range(0, len(arr), 1):
    min = arr[i]
    minIndx = i
    for j in range(i, len(arr), 1):
      if(arr[j]<min):
        min = arr[j]
        minIndx = j
    arr[i], arr[minIndx] = arr[minIndx], arr[i]
  return arr
my_list= [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
selectionasc(my_list)

#task 3
def bubblelist(arr):
  for i in range(0, len(arr), 1):
    for j in range(0, len(arr)-1, 1):
      if(arr[j+1]>arr[j]):
        arr[j+1], arr[j]= arr[j], arr[j+1]
  return arr
my_list = [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
bubblelist(my_list)

#task 4