# -*- coding: utf-8 -*-
"""CSE111-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19u_xr3QDWl4-IkYTjPfkHCYY982iNX8Z
"""

#task 1
def frac1(a, b):
  if b == 0:
    return 0
  else:
    return(a/b)-(a//b)
frac1(int(input()), int(input()))

#task 2
def BMI(height, weight):
  out= weight/((height/100)**2)
  condition= f"Score is {out:.1f}. "
  if out < 18.5:
    condition+= "You are Underweight"
  if 18.5 <= out <= 24.9:
    condition += "you are Normal"
  if 25 <= out <= 30:
    condition += "you are Overweight"
  if out > 30:
    condition += "you are Obese"
  return condition
BMI(int(input()), int(input()))

#task 3
def calc(min, max, div):
  out = 0
  for i in range(min, max):
    if i%div == 0:
      out+= i
  return out
calc(int(input()), int(input()), int(input()))

#task 4
def chill(menu, location= "Mohakhali"):
  total= 0
  dict1= {"BBQ Chicken Cheese Burger" : 250,
          "Beef Burger" : 170,
          "Naga Drums" : 200}
  if location == "" or "Mohakhali":
    total = dict1[menu] + 40 + .08*dict1[menu]
  else:
    total = dict1[menu] + 60 + .08*dict1[menu]
  return total
chill(input(), input())

#task 5
def replace_domain(check, new, old = "kaaj.com"):
  if f"@{old}" in check:
    new = "Changed: " + check.split("@")[0]+f"@{new}"
  elif f"@{new}" in check:
    new = "Unchanged: " + check
  return new
replace_domain(input(), input(), input())

#task 6
def vowelcalc(name):
  out = ""
  for i in name:
    if i in "AEIOUaeiou":
      out += f"{i}, "
  count = len(out.split(", "))-1
  if out == "":
    print("No vowels in the name")
    return
  print (f"Vowels: {out[:-2]}. Total number of vowels: {count}")
vowelcalc(input())

#task 7
def checkpal(input1):
  check = ""
  for i in input1:
    if i != " ":
      check += i
  if check == check[::-1]:
    print("Palindrome")
    return
  print("Not a palindrome")

checkpal(input())

#task 8
def daysconv(days):
  years = days//365
  months = days%365//30
  days = days%365%30
  print(f"{years} years, {months} months and {days} days")
daysconv(int(input()))

#task 9
def capcheck(input1):
  out = ""
  idx = 0
  for i in input1:
    if idx == len(input1)-1:
      out += i
      break
    if idx == 0 and ord(i) in range(97,123):
      out += chr(ord(i)-32)
    elif input1[idx-2] in ".?!" and idx-2 > 0 and ord(i) in range(97,123):
      out += chr(ord(i)-32)
    elif input1[idx-1] == input1[idx+1] == " " and i == "i":
      out += "I"
    else:
      out += i
    idx += 1
  print(out)

capcheck(input())