# -*- coding: utf-8 -*-
"""CSE111-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zjgbLflqFH5n4aQ0RchJKw9pET8YBsOM

**Strings**
"""

#task 1
x= input()
upper= 0
lower= 0
for i in x:
  if ord(i) in range(65, 91):
    upper+=1
  elif ord(i) in range(97, 123):
    lower+=1
if upper > lower:
  print(x.upper())
if lower>=upper:
  print(x.lower())

#task 2
input1= input()
digit= False
character= False

for i in input1:
  if ord(i) in range(48, 57):
    digit= True
  if ord(i) in range(65, 91) or ord(i) in range(97, 123):
    character= True
if character and digit:
  print("MIXED")
elif character:
  print("WORD")
elif digit:
  print("NUMBER")

#task 3
input1 = input()
start = False
blank = True
for i in input1:
  if not start and ord(i) in range(65,91):
    start = True
  elif start and ord(i) in range(97,123):
    print(i,end="")
    blank = False
  elif start and ord(i) in range(65,91):
    break
if blank:
  print("BLANK")

#task 4
common = False
input1 = input().split(", ")
for i in input1[0]:
  if i in input1[1]:
    print(i,end="")
    common = True
for i in input1[1]:
  if i in input1[0]:
    print(i,end="")
if not common:
  print("Nothing in common.")

#task 5
pass1 = input()
upper = 0
lower = 0
digit = 0
special = 0
s= ""
for i in pass1:
  if ord(i) in range(65,91):
    upper += 1
  if ord(i) in range(97,123):
    lower +=1
  if ord(i) in range(48,58):
    digit +=1
  if i in "_$#@":
    special +=1
if upper>=1 and lower>=1 and digit>=1 and special>=1:
  print("OK")
if lower<1:
  s+= "Lowercase character missing, "
if upper<1:
  s+= "Uppercase character missing, "
if digit<1:
  s+= "Digit Missing, "
if special<1:
  s+= "Special character missing, "
print(s[:-2])

"""**List**"""

#task 1
list1= []
while True:
  input1= input()
  if input1 == "STOP":
    break
  else:
    list1.append(int(input1))
count1= []
for i in list1:
  if i not in count1:
    count1.append(i)
    count= 0
    for j in list1:
      if j == i:
        count += 1
    print(f"{i} - {count} times")

#task 2
x = []
y = int(input())
for i in range(y):
  z = input().split()
  for j in range(len(z)):
    z[j] = int(z[j])
  x.append(z)
sum1 = sum(x[0])
l1 = x[0]
for i in x:
  sum2 = sum(i)
  l2 = i
  if sum2>sum1:
    sum1 = sum2
    l1 = l2
print(f"{sum1}\n{l1}")

#task 3
list1 = input().split()
list2 = input().split()
outlist = []
for i in list1:
  for j in list2:
    outlist.append(int(i)*int(j))
print(outlist)

#task 4
while True:
  outlist = []
  input1 = input().split(" ")
  if input1 == ["STOP"]:
    break
  for i in range(len(input1)-1):
    outlist.append(abs(int(input1[i])-int(input1[i+1])))
  for i in range(1,len(input1)):
    if i not in outlist:
      print("Not UB Jumper")
      break
  else:
    print("UB Jumper")

#task 5
start = input().split()
comp = input().split()
part = 0
for i in comp:
  if int(i)+int(start[1]) <= 5:
    part += 1
print(part//3)

"""**Dictionary and Tuple**"""

#task 1
dict1= {}
for i in range(2):
  input1= input().split(",")
  for i in range(len(input1)):
    input1[i]= input1[i].split(": ")
    if input1[i][0] not in dict1:
      dict1[input1[i][0]]= int(input1[i][1])
    else:
      dict1[input1[i][0]]+= int(input1[i][1])
values = list(set(dict1.values()))
values.sort()
print(f"{dict1}\nValues: {tuple(values)}")

#task 2
dict1 = {}
while True:
  input1 = input()
  if input1 == "STOP":
    break
  if  input1 not in dict1:
    dict1[input1] = 1
  else:
    dict1[input1] += 1
for i in dict1:
  print(f"{i} - {dict1[i]} times")

#task 3
x = input().split(", ")
dict1 = {}
dict2 = {}
for i in range(len(x)):
  x[i] = x[i].split(" : ")
  dict1[x[i][0]] = x[i][1]
for i in dict1:
  if dict1[i] not in dict2:
    dict2[dict1[i]] = [i]
  else:
    dict2[dict1[i]] += [i]

print(dict2)

#task 4
keypad = {
    '1' : ['.', ',', '?', '!', ':'],
    '2' : ['A', 'B', 'C'],
    '3' : ['D', 'E', 'F'],
    '4' : ['G', 'H', 'I'],
    '5' : ['J', 'K', 'L'],
    '6' : ['M', 'N', 'O'],
    '7' : ['P', 'Q', 'R', 'S'],
    '8' : ['T', 'U', 'V'],
    '9' : ['W', 'X', 'Y', 'Z'],
    '0' : [' ']
}

input1 = input().upper()

keyout = ""
keypress = list(keypad.items())

for i in range(len(input1)):
  for j in range(len(keypress)):
    for k in range(len(keypress[j][1])):
      if input1[i] == keypress[j][1][k]:
        keyout+=((k+1)*keypress[j][0])
print(keyout)

#task 4 find this solve later
x= input()
y= input()
emp = ""
for i in x:
  if i in y:
    emp+= i

for i in y:
  if i in x:
    emp+= i

print(emp)